package arima.anotherpack.core;

import cpw.mods.fml.common.registry.LanguageRegistry;
import net.minecraft.item.ItemStack;

public class LangRu {
	public static void registerItems() {
		LanguageRegistry.addName(AllItems.IceKingHelm, "§eКорона §bСнежного Короля");
		LanguageRegistry.addName(AllItems.BasteCrown, "§eКорона §4Baste");
		LanguageRegistry.addName(AllItems.SnowMaidenBoots, "§bСапожки Снегурочки");
		LanguageRegistry.addName(AllItems.SnowMaidenHelmet, "§bШапка Снегурочки");
		LanguageRegistry.addName(AllItems.SnowMaidenPants, "§bЮбка Снегурочки");
		LanguageRegistry.addName(AllItems.SnowMaidenPlate, "§bШуба Снегурочки");
		LanguageRegistry.instance().addStringLocalization("entity.anotherpack.EntityGyroscooter.name", "Gyroscooter");
		LanguageRegistry.addName(AllItems.Steampunk_Sword, "Стимпанк меч");
		LanguageRegistry.addName(AllItems.DrillSword, "Пронзающий небеса");
		LanguageRegistry.addName(AllItems.EffFood_1, "Пиво");
		LanguageRegistry.addName(AllItems.EffFood_2, "Бенто");
		LanguageRegistry.addName(AllItems.EffFood_3, "Бургер");
		LanguageRegistry.addName(AllItems.EffFood_4, "Бутерброд");
		LanguageRegistry.addName(AllItems.EffFood_5, "Хотдог");
		LanguageRegistry.addName(AllItems.EffFood_6, "Сок");
		LanguageRegistry.addName(AllItems.EffFood_7, "Компот");
		LanguageRegistry.addName(AllItems.EffFood_8, "Конфета");
		LanguageRegistry.addName(AllItems.EffFood_9, "Курочка");
		LanguageRegistry.addName(AllItems.EffFood_10, "Лайм");
		LanguageRegistry.addName(AllItems.EffFood_11, "Лимонад");
		LanguageRegistry.addName(AllItems.EffFood_12, "Мороженное");
		LanguageRegistry.addName(AllItems.EffFood_13, "Куриная ножка");
		LanguageRegistry.addName(AllItems.EffFood_14, "Кусок пиццы");
		LanguageRegistry.addName(AllItems.EffFood_15, "Рамен");
		LanguageRegistry.addName(AllItems.EffFood_16, "Самогон");
		LanguageRegistry.addName(AllItems.EffFood_17, "Шоколад");
		LanguageRegistry.addName(AllItems.EffFood_18, "Сыр");
		LanguageRegistry.addName(AllItems.EffFood_19, "Вафля");
		LanguageRegistry.addName(AllItems.Migalka, "Мигалка полиции");
		LanguageRegistry.addName(AllItems.RainbowCore, "Радужное ядро");
		LanguageRegistry.addName(AllItems.KeyForGifCase, "Ключ для кейса с гифками");
		LanguageRegistry.addName(AllItems.Gyroscooter, "Гироскутер");
		LanguageRegistry.addName(AllItems.Rainbow_Blaster, "Радужный бластер");
		LanguageRegistry.addName(AllItems.Rainbow_Pika, "Радужное копьё");
		LanguageRegistry.addName(AllItems.Rainbow_Heal, "Радужный кадуцей");
		LanguageRegistry.addName(AllItems.Rainbow_Sword, "Радужный меч");
		LanguageRegistry.addName(AllItems.BigHammer, "Молот Билли");
		LanguageRegistry.addName(AllItems.halloweenbox, "Хэллоуинский набор");
		LanguageRegistry.addName(AllItems.rune9, "Руна 9 Уровня");
		LanguageRegistry.addName(AllItems.rune10, "Руна 10 Уровня");
		LanguageRegistry.addName(AllItems.PickAxe3x3, "Кирка 3x3");
		LanguageRegistry.addName(AllItems.chickenSword, "Chicken Sword");
		LanguageRegistry.addName(AllItems.itemPhotoElement_1, "Фотоэлемент 1 уровня");
		LanguageRegistry.addName(AllItems.itemPhotoElement_2, "Фотоэлемент 2 уровня");
		LanguageRegistry.addName(AllItems.itemPhotoElement_3, "Фотоэлемент 3 уровня");
		LanguageRegistry.addName(AllItems.itemPhotoElement_4, "Фотоэлемент 4 уровня");
		LanguageRegistry.addName(AllItems.hardGlassPlate, "Пластина укрепленного стекла");
		LanguageRegistry.addName(AllItems.bdsmWhip, "Плетка §cЖ");
		LanguageRegistry.addName(AllItems.bdsmWhip2, "Плетка §cКисы");
		LanguageRegistry.addName(AllItems.quantCoreModuleScythe, "§cАлое квантовое ядро");
		LanguageRegistry.addName(AllItems.QuantDrill, "§9Квантовый бур 3x3§f");
		LanguageRegistry.addName(AllItems.WorldSensorCard, "§4Crescent Rose§9 Модуль Энергии§f");
		LanguageRegistry.addName(AllItems.ScytheModuleWither, "§4Crescent Rose§8 Модуль Иссушение§f");
		LanguageRegistry.addName(AllItems.ScytheModuleRegeneration, "§4Crescent Rose§c Модуль Вампиризма§f");
		LanguageRegistry.addName(AllItems.Scythe_1, "§4Crescent Rose§8 Иссушения§f");
		LanguageRegistry.addName(AllItems.Scythe_2, "§4Crescent Rose§c Вампиризма§f");
		LanguageRegistry.addName(AllItems.ItemScythePart_a, "§4Crescent Rose §9Часть А§f");
		LanguageRegistry.addName(AllItems.ItemScythePart_b, "§4Crescent Rose §9Часть B§f");
		LanguageRegistry.addName(AllItems.ItemScythePart_c, "§4Crescent Rose §9Часть C§f");
		LanguageRegistry.addName(AllItems.ItemScythePart_d, "§4Crescent Rose §9Часть D§f");
		LanguageRegistry.addName(AllItems.ItemScythePart_e, "§4Crescent Rose §9Часть E§f");
		LanguageRegistry.addName(AllItems.ItemScythePart_f, "§4Crescent Rose §9Часть F§f");
		LanguageRegistry.addName(AllItems.ItemScytheFireDustAmmo, "§4Crescent Rose §cОгнестрельный отсек§f");
		LanguageRegistry.addName(AllItems.bullet_shell, "§9Пуля для §4Crescent Rose§c Вампиризма§f");
		LanguageRegistry.addName(AllItems.bullet, "§9Пуля для §4Crescent Rose§8 Иссушение§f");
		LanguageRegistry.addName(AllItems.IridiumPlate2, "Супер плотная иридиевая пластина");
		LanguageRegistry.addName(AllItems.Materia, "§dМатерия");
		LanguageRegistry.addName(AllItems.Fire_materia, "§6Солнечная Материя");
		LanguageRegistry.addName(AllItems.Live_materia, "§aЖивая Материя");
		LanguageRegistry.addName(AllItems.Sky_materia, "§bНебесная Материя");
		LanguageRegistry.addName(AllItems.Dark_materia, "§8Тёмная Материя");
		LanguageRegistry.addName(AllItems.Dye1, "Тёмный краситель");
		LanguageRegistry.addName(AllItems.Dye2, "Бирюзовый краситель");
		LanguageRegistry.addName(AllItems.Dye3, "Серый краситель");
		LanguageRegistry.addName(AllItems.Dye4, "Хмельная кислота");
		LanguageRegistry.addName(AllItems.Dye5, "Голубой краситель");
		LanguageRegistry.addName(AllItems.Dye6, "Светло-зеленый краситель");
		LanguageRegistry.addName(AllItems.Dye7, "Светло-фиолетовый краситель");
		LanguageRegistry.addName(AllItems.Dye8, "Оранжевый краситель");
		LanguageRegistry.addName(AllItems.Dye9, "Розовый краситель");
		LanguageRegistry.addName(AllItems.Dye10, "Фиолетовый краситель");
		LanguageRegistry.addName(AllItems.Dye11, "Красный краситель");
		LanguageRegistry.addName(AllItems.Dye12, "Белый краситель");
		LanguageRegistry.addName(AllItems.Dye13, "Желтый краситель");
		LanguageRegistry.addName(AllItems.Powder1, "Оранжевый порошок");
		LanguageRegistry.addName(AllItems.Powder2, "Голубой порошок");
		LanguageRegistry.addName(AllItems.Powder3, "Светло-зеленый порошок");
		LanguageRegistry.addName(AllItems.Powder4, "Розовый порошок");
		LanguageRegistry.addName(AllItems.Powder5, "Светло-розовый порошок");
		LanguageRegistry.addName(AllItems.Powder6, "Фиолетовый порошок");
		LanguageRegistry.addName(AllItems.Powder7, "Красный порошок");
		LanguageRegistry.addName(AllItems.Powder8, "Белый порошок");
		LanguageRegistry.addName(AllItems.Powder9, "Светло-желтый порошок");
		LanguageRegistry.addName(AllItems.Powder10, "Жёлтый порошок");
		LanguageRegistry.addName(AllItems.Powder11, "Тёмный порошок");
		LanguageRegistry.addName(AllItems.Powder12, "Бирюзовый порошок");
		LanguageRegistry.addName(AllItems.Powder13, "Серый порошок");
		LanguageRegistry.addName(AllItems.Powder14, "Зелёный порошок");
		LanguageRegistry.addName(AllItems.Oc1, "Чип 2 уровня");
		LanguageRegistry.addName(AllItems.Oc2, "Чип 3 уровня");
		LanguageRegistry.addName(AllItems.Oc3, "Чип 1 уровня");
		LanguageRegistry.addName(AllItems.Oc4, "Схема 4");
		LanguageRegistry.addName(AllItems.Tanzanit, "Танзанит");
		LanguageRegistry.addName(AllItems.Topaz, "Топаз");
		LanguageRegistry.addName(AllItems.Malahit, "Малахит");
		LanguageRegistry.addName(AllItems.Akvamarin, "Аквамарин");
		LanguageRegistry.addName(AllItems.Amethyst, "Аметист");
		LanguageRegistry.addName(AllItems.Pluton_ingot, "Слиток плутона");
		LanguageRegistry.addName(AllItems.Uran_ingot, "Слиток урана");
		LanguageRegistry.addName(AllItems.Mox_ingot, "Слиток");
		LanguageRegistry.addName(AllItems.Ice_ingot, "Слиток льда");
		LanguageRegistry.addName(AllItems.Dark_ingot, "Тёмный слиток");
		LanguageRegistry.addName(AllItems.Demonic_ingot, "Демонический слиток");
		LanguageRegistry.addName(AllItems.Map, "Карта");
		LanguageRegistry.addName(AllItems.Book1, "Книга 1");
		LanguageRegistry.addName(AllItems.Book2, "Книга 2");
		LanguageRegistry.addName(AllItems.Book3, "Книга 3");
		LanguageRegistry.addName(AllItems.Book4, "Книга 4");
		LanguageRegistry.addName(AllItems.Circuit1, "Схема 3");
		LanguageRegistry.addName(AllItems.Circuit2, "Схема 2");
		LanguageRegistry.addName(AllItems.Circuit3, "Схема 1");
		LanguageRegistry.addName(AllItems.Holst, "Холст");
		LanguageRegistry.addName(AllItems.Fire_sanarium, "Горящий саннарий");
		LanguageRegistry.addName(AllItems.Demonic_ruby, "Демонический рубин");
		LanguageRegistry.addName(AllItems.Dark_mox, "Тёмный шар");
		LanguageRegistry.addName(AllItems.Dark_spirit, "Тёмная душа");
		LanguageRegistry.addName(AllItems.Vace_Materia, "Вис-материя");
		LanguageRegistry.addName(AllItems.Sun_materia, "Солнечная материя");
		LanguageRegistry.addName(AllItems.Magic_materia, "Магическая материя");
		LanguageRegistry.addName(AllItems.Outline, "Кибер-контур");
		LanguageRegistry.addName(AllItems.Realm_quantum, "Область кванта");
		LanguageRegistry.addName(AllItems.Recipe1, "Рецепт 1");
		LanguageRegistry.addName(AllItems.Recipe2, "Рецепт 2");
		LanguageRegistry.addName(AllItems.Recipe3, "Рецепт 3");
		LanguageRegistry.addName(AllItems.Recipe4, "Рецепт 4");
		LanguageRegistry.addName(AllItems.Recipe5, "Рецепт 5");
		LanguageRegistry.addName(AllItems.Granat, "Гранат");
		LanguageRegistry.addName(AllItems.Ordo_Materia, "Ordo Materia");
		LanguageRegistry.addName(AllItems.Entropy_Materia, "Entropy Materia");
		LanguageRegistry.addName(AllItems.Aer_Materia, "Aer Materia");
		LanguageRegistry.addName(AllItems.EnderBag, "Сумка эндера");
		LanguageRegistry.addName(AllItems.box1, "Горсть золота");
		LanguageRegistry.addName(AllItems.box2, "Малый мешок золота");
		LanguageRegistry.addName(AllItems.box3, "Большой мешок золота");
		LanguageRegistry.addName(AllItems.ColorSword_Diamond, "Алмазный кибер-меч");
		LanguageRegistry.addName(AllItems.ColorSword_Iron, "Железный кибер-меч");
		LanguageRegistry.addName(AllItems.ColorSword_Gold, "Золотой кибер-меч");
		LanguageRegistry.addName(AllItems.ColorSword_Stone, "Змеиный кибер-меч");
		LanguageRegistry.addName(AllItems.EpicGoldApple, "Золотое кибер-яблоко");
		LanguageRegistry.addName(AllItems.spinner_1, "Спиннер белый");
		LanguageRegistry.addName(AllItems.spinner_2, "Спиннер черный");
		LanguageRegistry.addName(AllItems.PrivateWand, "Топор для выделения привата");
		LanguageRegistry.addName(AllItems.PrivateInfo, "Бирка для проверки привата");
		LanguageRegistry.addName(AllItems.cosa, "Коса Смерти");
		LanguageRegistry.addName(AllItems.cosa2, "Полумесечная роза");
		LanguageRegistry.addName(AllItems.cosa3, "Цветущая роза");
		LanguageRegistry.addName(AllItems.neon_sw, "Неоновый палаш");
		LanguageRegistry.addName(AllItems.cyb_sw, "Кибер палаш");
		LanguageRegistry.addName(AllItems.str_sw, "Нано палаш");
		LanguageRegistry.addName(AllItems.tes_sw, "Меч Гаусса");
		LanguageRegistry.addName(AllItems.p_sw, "Дюрандаль");
		LanguageRegistry.addName(AllItems.y_sw, "Клинок Золотого Дракона");
		LanguageRegistry.addName(AllItems.rune11, "Легендарная руна");
		LanguageRegistry.addName(AllItems.book1, "Книга прочности");
		LanguageRegistry.addName(AllItems.amulet1, "Амулет Шаи");
		LanguageRegistry.addName(AllItems.amulet2, "Улучшенный амулет Шаи");
		LanguageRegistry.addName(AllItems.amulet3, "Пробужденный амулет Шаи");
		LanguageRegistry.addName(AllItems.amulet4, "Амулет Гредона");
		LanguageRegistry.addName(AllItems.amulet5, "Улучшенный амулет Гредона");
		LanguageRegistry.addName(AllItems.amulet6, "Пробужденный амулет Гредона");
		LanguageRegistry.addName(AllItems.amulet7, "Амулет Туи");
		LanguageRegistry.addName(AllItems.amulet8, "Улучшенный амулет Туи");
		LanguageRegistry.addName(AllItems.amulet9, "Пробужденный амулет Туи");
		LanguageRegistry.addName(AllItems.amulet10, "Триада очарования");
		LanguageRegistry.addName(AllItems.amulet11, "Ожерелье Скади");
		LanguageRegistry.addName(AllItems.rune1, "Руна 1 Уровня");
		LanguageRegistry.addName(AllItems.red_materia, "Красная материя");
		LanguageRegistry.addName(AllItems.swordbox, "Набор с мечами");
		LanguageRegistry.addName(AllItems.runebox, "Набор с рунами");
		LanguageRegistry.addName(AllItems.amuletbox, "Набор с амулетами");
		LanguageRegistry.addName(AllItems.BoxInstr, "Кейс с инструментами");
		LanguageRegistry.addName(AllItems.BoxArmor, "Кейс с броней");
		LanguageRegistry.addName(AllItems.BoxMechanism, "Кейс с механизмами");
		LanguageRegistry.addName(AllItems.BoxCoins, "Кейс с монетами");
		LanguageRegistry.addName(AllItems.BoxComponent, "Кейс с компонентами");
		LanguageRegistry.addName(AllItems.BoxRes, "Кейс с ресурсами");
		LanguageRegistry.addName(AllItems.BoxCharge, "Кейс с зарядками");
		LanguageRegistry.addName(AllItems.BoxGif, "Кейс с гифками");
		LanguageRegistry.addName(AllItems.BoxCNPCs, "Кейс с оружием");
		LanguageRegistry.addName(AllItems.BoxRainbowWeapon, "Кейс с радужным оружием");
		LanguageRegistry.addName(AllItems.BoxCases, "Кейс с кейсами");
		LanguageRegistry.addName(AllItems.BoxVote, "Кейс с голосования");
		LanguageRegistry.addName(AllItems.ItemMagicStick, "Магическая палка");
		LanguageRegistry.addName(AllItems.ItemDoorAcacia, "Дверь из акации");
		LanguageRegistry.addName(AllItems.ItemDoorBirch, "Дверь из берёзы");
		LanguageRegistry.addName(AllItems.ItemDoorDarkOak, "Дверь из тёмного дуба");
		LanguageRegistry.addName(AllItems.ItemDoorIron, "Железная дверь");
		LanguageRegistry.addName(AllItems.ItemDoorJungle, "Дверь из тропического деревеа");
		LanguageRegistry.addName(AllItems.ItemDoorSpruce, "Еловая дверь");
		LanguageRegistry.addName(AllItems.ItemDoorGlass, "Стеклянная дверь");
		LanguageRegistry.addName(AllItems.ItemDoorIronBars, "Решетчатая дверь");
		LanguageRegistry.addName(AllItems.ItemDoorNetherBricks, "Дверь из адского камня");
		LanguageRegistry.addName(AllItems.ItemDoorObsidian, "Дверь из обсидиана");
		LanguageRegistry.addName(AllItems.ItemDoorFactory, "Заводская дверь");
		LanguageRegistry.addName(AllItems.ItemDoorJail, "Тюремная дверь");
		LanguageRegistry.addName(AllItems.ItemDoorLabaratory, "Дверь для лаборатории");
		LanguageRegistry.addName(AllItems.ItemDoorShoji, "Дверь Сёдзи");
		LanguageRegistry.addName(AllItems.ItemDoorSlidingIron, "Дверь из скользящего железа");
		LanguageRegistry.addName(AllItems.ItemDoorSlidingWood, "Дверь из скользящего дерева");
	}

	public static void registerBlocks() {
		int z = 17;
		int x = 33;
		int c = 49;
		int v = 65;
		int b = 81;
		for (int a = 0; a < 16; a++) {
			LanguageRegistry.addName(new ItemStack(AllBlocks.WoodenBlock_1, 1, a), "Деревянный блок " + a);
			LanguageRegistry.addName(new ItemStack(AllBlocks.IronBlock_1, 1, a), "Железный блок " + a);
			LanguageRegistry.addName(new ItemStack(AllBlocks.StoneBlocks_1, 1, a), "Каменный блок " + a);
			LanguageRegistry.addName(new ItemStack(AllBlocks.MarbleBlock_1, 1, a), "Мраморный блок " + a);
			LanguageRegistry.addName(new ItemStack(AllBlocks.ColorBlock, 1, a), "Цветной блок " + a);
		}
		for (int a = 0; a < 16; a++) {
			LanguageRegistry.addName(new ItemStack(AllBlocks.WoodenBlock_2, 1, a), "Деревянный блок " + z);
			LanguageRegistry.addName(new ItemStack(AllBlocks.IronBlock_2, 1, a), "Железный блок " + z);
			LanguageRegistry.addName(new ItemStack(AllBlocks.StoneBlocks_2, 1, a), "Каменный блок " + z);
			z++;
		}
		for (int a = 0; a < 16; a++) {
			LanguageRegistry.addName(new ItemStack(AllBlocks.IronBlock_3, 1, a), "Железный блок " + x);
			LanguageRegistry.addName(new ItemStack(AllBlocks.StoneBlocks_3, 1, a), "Каменный блок " + x);
			x++;
		}
		for (int a = 0; a < 16; a++) {
			LanguageRegistry.addName(new ItemStack(AllBlocks.StoneBlocks_4, 1, a), "Каменный блок " + c);
			c++;
		}
		for (int a = 0; a < 16; a++) {
			LanguageRegistry.addName(new ItemStack(AllBlocks.StoneBlocks_5, 1, a), "Каменный блок " + v);
			v++;
		}
		for (int a = 0; a < 16; a++) {
			LanguageRegistry.addName(new ItemStack(AllBlocks.StoneBlocks_6, 1, a), "Каменный блок " + b);
			b++;
		}
		for (int a = 0; a < 6; a++) {
			LanguageRegistry.addName(new ItemStack(AllBlocks.VoidBlock, 1, a), "Магический блок " + a);
			LanguageRegistry.addName(new ItemStack(AllBlocks.Lamp1, 1, a), "Лампа " + a);
		}
		for (int a = 0; a < 9; a++) {
			LanguageRegistry.addName(new ItemStack(AllBlocks.PortalBlock, 1, a), "Портал " + a);
		}
		for (int a = 0; a < 16; a++) {
			LanguageRegistry.addName(new ItemStack(AllBlocks.OsBricks, 1, a), "Кирпичный блок " + a);
		}
		LanguageRegistry.addName(new ItemStack(AllBlocks.BlockColorPortal, 1, 0), "Тёмный портал (блок)");
		LanguageRegistry.addName(new ItemStack(AllBlocks.BlockColorPortal, 1, 1), "Розовый портал (блок)");
		LanguageRegistry.addName(new ItemStack(AllBlocks.BlockColorPortal, 1, 2), "Фиолетовый портал (блок)");
		LanguageRegistry.addName(AllBlocks.ColorPortal_1, "Тёмный портал");
		LanguageRegistry.addName(AllBlocks.ColorPortal_2, "Розовый портал");
		LanguageRegistry.addName(AllBlocks.ColorPortal_3, "Фиолетовый портал");
		LanguageRegistry.addName(new ItemStack(AllBlocks.MarbleBlock_2, 1, 0), "Мраморный блок 16");
		LanguageRegistry.addName(new ItemStack(AllBlocks.MarbleBlock_2, 1, 1), "Мраморный блок 17");
		LanguageRegistry.addName(new ItemStack(AllBlocks.MarbleBlock_2, 1, 2), "Мраморный блок 18");
		LanguageRegistry.addName(new ItemStack(AllBlocks.MarbleBlock_2, 1, 3), "Мраморный блок 19");
		LanguageRegistry.addName(AllBlocks.Stairs_Wood3, "Ступеньки из дерева 3");
		LanguageRegistry.addName(AllBlocks.Stairs_Wood5, "Ступеньки из дерева 5");
		LanguageRegistry.addName(AllBlocks.Stairs_Stone5, "Ступеньки из камня 5");
		LanguageRegistry.addName(AllBlocks.Stairs_Stone48, "Ступеньки из камня 5");
		LanguageRegistry.addName(AllBlocks.Stairs_iron33, "Железные ступеньки");
		LanguageRegistry.addName(AllBlocks.Stairs_Kamni, "Каменные ступеньки");
		LanguageRegistry.addName(AllBlocks.Stairs_Linoleum, "Ступеньки из дерева");
		LanguageRegistry.addName(AllBlocks.Stairs_Kirpich, "Ступеньки из кирпича");
		LanguageRegistry.addName(AllBlocks.Stairs_Keramika, "Ступеньки из керамики");
		LanguageRegistry.addName(AllBlocks.Stairs_LinoleumDirt, "Ступеньки из грязного дерева");
		LanguageRegistry.addName(AllBlocks.Stairs_LinoleumClear, "Ступеньки из чистого дерева");
		LanguageRegistry.addName(AllBlocks.Stair_planks_oak, "Ступеньки из дубовых досок");
		LanguageRegistry.addName(AllBlocks.Stair_planks_spruce, "Ступеньки из еловых досок");
		LanguageRegistry.addName(AllBlocks.Stair_wood_birch, "Ступеньки из берёзовых досок");
		LanguageRegistry.addName(AllBlocks.Stair_wood_jungle, "Ступеньки из досок тропического дерева");
		LanguageRegistry.addName(AllBlocks.Stair_wood_oak, "Ступеньки из древесины дуба");
		LanguageRegistry.addName(AllBlocks.Stair_wood_spruce, "Ступеньки из древесины ели");
		LanguageRegistry.addName(AllBlocks.Stair_asphalt, "Ступенька из асфальта");
		LanguageRegistry.addName(AllBlocks.Stair_cobblestone, "Ступеньки из булыжника");
		LanguageRegistry.addName(AllBlocks.Stair_stonebrick1, "Ступеньки из каменного кирпича 1");
		LanguageRegistry.addName(AllBlocks.Stair_stonebrick2, "Ступеньки из каменного кирпича 2");
		LanguageRegistry.addName(AllBlocks.Stair_stonebrick3, "Ступеньки из каменного кирпича 3");
		LanguageRegistry.addName(AllBlocks.ColorStairWhite, "Белая ступенька");
		LanguageRegistry.addName(AllBlocks.lanterns_black, "Тёмная лампа");
		LanguageRegistry.addName(AllBlocks.lanterns_blue, "Синяя лампа");
		LanguageRegistry.addName(AllBlocks.lanterns_orange, "Оранжевая лампа");

		LanguageRegistry.addName(AllBlocks.WeaponUpdater, "§fСборщик оружия");
		LanguageRegistry.addName(AllBlocks.StAndrewsCross_01, "§9Андреевский крест 1");
		LanguageRegistry.addName(AllBlocks.StAndrewsCross_02, "§9Андреевский крест 2");
		LanguageRegistry.addName(AllBlocks.StAndrewsCross_03, "§9Андреевский крест 3");
		LanguageRegistry.addName(AllBlocks.StAndrewsCross_04, "§9Андреевский крест 4");
		LanguageRegistry.addName(AllBlocks.StAndrewsCross_05, "§9Андреевский крест 5");
		LanguageRegistry.addName(AllBlocks.StAndrewsCross_06, "§9Андреевский крест 6");
		LanguageRegistry.addName(AllBlocks.Box1, "Коробка 1");
		LanguageRegistry.addName(AllBlocks.Box2, "Коробка 2");
		LanguageRegistry.addName(AllBlocks.Box3, "Коробка 3");
		LanguageRegistry.addName(AllBlocks.Box4, "Коробка 4");
		LanguageRegistry.addName(AllBlocks.Box5, "Коробка 5");
		LanguageRegistry.addName(AllBlocks.Box6, "Коробка 6");
		LanguageRegistry.addName(AllBlocks.Box7, "Коробка 7");
		LanguageRegistry.addName(AllBlocks.Fence_planks_oak, "Забор из древесины дуба");
		LanguageRegistry.addName(AllBlocks.Fence_planks_spruce, "Забор из древесины ели");
		LanguageRegistry.addName(AllBlocks.Fence_wood_birch, "Забор из древесины берёзы");
		LanguageRegistry.addName(AllBlocks.Fence_wood_jungle, "Забор из древесины тропического дерева");
		LanguageRegistry.addName(AllBlocks.Fence_wood_oak, "Дубовый забор");
		LanguageRegistry.addName(AllBlocks.Fence_wood_spruce, "Берёзовый забор");
		LanguageRegistry.addName(AllBlocks.Fence_stonebrick1, "Забор из каменного кирпича 1");
		LanguageRegistry.addName(AllBlocks.Fence_stonebrick2, "Забор из каменного кирпича 2");
		LanguageRegistry.addName(AllBlocks.Fence_stonebrick3, "Забор из каменного кирпича 3");
		LanguageRegistry.addName(AllBlocks.Cloth1, "Ткань 1");
		LanguageRegistry.addName(AllBlocks.Cloth2, "Ткань 2");
		LanguageRegistry.addName(AllBlocks.Cloth3, "Ткань 3");
		LanguageRegistry.addName(AllBlocks.Rope1, "Верёвка 1");
		LanguageRegistry.addName(AllBlocks.Rope2, "Верёвка 2");
		LanguageRegistry.addName(AllBlocks.Rope3, "Верёвка 3");
		LanguageRegistry.addName(AllBlocks.Rope4, "Веник");
		LanguageRegistry.addName(AllBlocks.Rope5, "Сушенный заяц");
		LanguageRegistry.addName(AllBlocks.Rope6, "Сушенная лягушка");
		LanguageRegistry.addName(AllBlocks.Chain1, "Цепь 1");
		LanguageRegistry.addName(AllBlocks.Chain2, "Цепь 2");
		LanguageRegistry.addName(AllBlocks.Chain3, "Цепь 3");
		LanguageRegistry.addName(AllBlocks.Rope_rail, "Канатный рельс");
		LanguageRegistry.addName(AllBlocks.Chain_rail, "Цепной рельс");
		LanguageRegistry.addName(AllBlocks.Grid_rail, "Сетка");
		LanguageRegistry.addName(AllBlocks.Barrel, "Бочка");
		LanguageRegistry.addName(AllBlocks.Bookshelf, "Книжная полка");
		LanguageRegistry.addName(AllBlocks.Shelf, "Полка");
		LanguageRegistry.addName(AllBlocks.Tnt, "Динамит");
		LanguageRegistry.addName(AllBlocks.Torch_fire, "Горящий факел");
		LanguageRegistry.addName(AllBlocks.Torch_ice, "Ледяной факел");
		LanguageRegistry.addName(AllBlocks.Provolka, "Колючая проволка");
		LanguageRegistry.addName(AllBlocks.BloodWater, "Кровавая вода");
		LanguageRegistry.addName(AllBlocks.lava_still, "Магма течет в наших венах, расскаляя сердца");
		LanguageRegistry.addName(AllBlocks.rails1, "Рельсы 1");
		LanguageRegistry.addName(AllBlocks.rails2, "Рельсы 2");
		LanguageRegistry.addName(AllBlocks.rails3, "Рельсы 3");
		LanguageRegistry.addName(AllBlocks.rails4, "Рельсы 4");
		LanguageRegistry.addName(AllBlocks.rails5, "Рельсы 5");
		LanguageRegistry.addName(AllBlocks.rails6, "Рельсы 6");
		LanguageRegistry.addName(AllBlocks.rails7, "Рельсы 7");
		LanguageRegistry.addName(AllBlocks.vityajka, "Вытяжка");
		LanguageRegistry.addName(AllBlocks.grass1, "Трава 1");
		LanguageRegistry.addName(AllBlocks.grass2, "Трава 2");
		LanguageRegistry.addName(AllBlocks.grass3, "Трава 3");
		LanguageRegistry.addName(AllBlocks.grass4, "Трава 4");
		LanguageRegistry.addName(AllBlocks.cl_fish, "Сушенная рыба");
		LanguageRegistry.addName(AllBlocks.cl_chicken, "Сушенная курица");
		LanguageRegistry.addName(AllBlocks.cloth_axe, "Настенный топор");
		LanguageRegistry.addName(AllBlocks.cloth_bita, "Настенная бита");
		LanguageRegistry.addName(AllBlocks.cloth_shovel, "Настенная лопата");
		LanguageRegistry.addName(AllBlocks.cloth_web, "Настенная паутина");
		LanguageRegistry.addName(AllBlocks.lampa1, "Включенная лампа");
		LanguageRegistry.addName(AllBlocks.lampa1_top, "Висячая включенная лампа");
		LanguageRegistry.addName(AllBlocks.lampa2, "Выключенная лампа");
		LanguageRegistry.addName(AllBlocks.lampa2_top, "Висячая выключенная лампа");
		LanguageRegistry.addName(AllBlocks.rail_axe, "Лежащий топор");
		LanguageRegistry.addName(AllBlocks.rail_blaze_powder, "Лежащий блейзер");
		LanguageRegistry.addName(AllBlocks.rail_bread, "Лежащая фляга");
		LanguageRegistry.addName(AllBlocks.rail_break_glass, "Лежащее разбитое стекло");
		LanguageRegistry.addName(AllBlocks.rail_charcoal, "Лежащий уголь");
		LanguageRegistry.addName(AllBlocks.rail_chicken_cooked, "Лежащий уголь");
		LanguageRegistry.addName(AllBlocks.rail_Gilzi1, "Лежащие гильзы");
		LanguageRegistry.addName(AllBlocks.rail_Gilzi2, "Лежащие патроны");
		LanguageRegistry.addName(AllBlocks.rail_Gilzi3, "Лежащие гильзы и патроны");
		LanguageRegistry.addName(AllBlocks.rail_gold, "Лежащая панель");
		LanguageRegistry.addName(AllBlocks.rail_halberd, "Лежащий ключ");
		LanguageRegistry.addName(AllBlocks.rail_leather, "Лежащая кожа");
		LanguageRegistry.addName(AllBlocks.rail_melon, "Лежащая бутыль");
		LanguageRegistry.addName(AllBlocks.rail_paper, "Лежащий листок");
		LanguageRegistry.addName(AllBlocks.rail_paper_2, "Лежащий листок 2");
		LanguageRegistry.addName(AllBlocks.laza, "Лоза");
		LanguageRegistry.addName(AllBlocks.SakuraLeaves, "Листва Сакуры");
		// LanguageRegistry.addName(AllBlocks.BlockSakuraLog, "Дерево Сакуры");
		LanguageRegistry.addName(AllBlocks.emptySlab, "Прозрачный полублок");
		LanguageRegistry.addName(AllBlocks.kislota, "Кислота");
		LanguageRegistry.addName(AllBlocks.Ladder1, "Лестница 1");
		LanguageRegistry.addName(AllBlocks.Ladder2, "Лестница 2");
		LanguageRegistry.addName(AllBlocks.whiteSlab, "Белая плита");
		LanguageRegistry.addName(AllBlocks.entityBlock, "Барьер");
		LanguageRegistry.addName(AllBlocks.blockRadiation, "Радиоактивный блок");
		LanguageRegistry.addName(AllBlocks.entityBlockLightGhost, "Светящийся прозрачный проходной блок");
		LanguageRegistry.addName(AllBlocks.asuka_gif_1, "Этти Аска 1");
		LanguageRegistry.addName(AllBlocks.asuka_gif_2, "Этти Аска 2");
		LanguageRegistry.addName(AllBlocks.asuka_gif_3, "Этти Аска 3");
		LanguageRegistry.addName(AllBlocks.asuka_gif_4, "Этти Аска 4");
		LanguageRegistry.addName(AllBlocks.asuka_gif_5, "Этти Аска 5");
		LanguageRegistry.addName(AllBlocks.asuka_gif_6, "Этти Аска 6");
		LanguageRegistry.addName(AllBlocks.DarlingInFranx_gif, "002 :P");
		LanguageRegistry.addName(AllBlocks.NyaGif_1, "Acchi 1");
		LanguageRegistry.addName(AllBlocks.NyaGif_2, "Acchi 2");
		LanguageRegistry.addName(AllBlocks.ZeroTwo_1, "002 милаха 1");
		LanguageRegistry.addName(AllBlocks.ZeroTwo_2, "002 милаха 2");
		LanguageRegistry.addName(AllBlocks.ZeroTwo_3, "002 милаха 3");
		LanguageRegistry.addName(AllBlocks.ZeroTwo_4, "002 милаха 4");
		LanguageRegistry.addName(AllBlocks.Yuri_meme, "Юри любит");
		LanguageRegistry.addName(AllBlocks.MeMeMe_Bunny_1, "Me! Me! Me! Кролик 1");
		LanguageRegistry.addName(AllBlocks.MeMeMe_Bunny_2, "Me! Me! Me! Кролик 2");
		LanguageRegistry.addName(AllBlocks.MeMeMe_Bunny_3, "Me! Me! Me! Кролик 3");
		LanguageRegistry.addName(AllBlocks.MeMeMe_Bunny_4, "Me! Me! Me! Кролик 4");
		LanguageRegistry.addName(AllBlocks.MeMeMe_Bunny_5, "Me! Me! Me! Кролик 5");
		LanguageRegistry.addName(AllBlocks.MeMeMe_Bunny_6, "Me! Me! Me! Кролик 6");
		LanguageRegistry.addName(AllBlocks.Eva_head, "Голова Eva 01");
		LanguageRegistry.addName(AllBlocks.Megumin_1, "Мегумин 1");
		LanguageRegistry.addName(AllBlocks.Megumin_2, "Мегумин 2");
		LanguageRegistry.addName(AllBlocks.Megumin_2, "Мегумин 2");
		LanguageRegistry.addName(AllBlocks.SlabStone3_1, "Плита из черной плиты");
		LanguageRegistry.addName(AllBlocks.graffiti_open_1, "Табличка Открыто 1");
		LanguageRegistry.addName(AllBlocks.graffiti_open_2, "Табличка Открыто 2");
		LanguageRegistry.addName(AllBlocks.graffiti_welcome_1, "Табличка Добро пожаловать 1");
		LanguageRegistry.addName(AllBlocks.graffiti_welcome_2, "Табличка Добро пожаловать 2");
		LanguageRegistry.addName(AllBlocks.whiteFence, "Забор из белого блока");
		LanguageRegistry.addName(AllBlocks.blacMosaicFence, "Забор из черного мозаичного блока");
	}
}
